#!/usr/bin/env bash
# Sync hackathon backend/.env → .cursor/mcp.env for Cursor MCP servers.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BACKEND_ENV="$ROOT/backend/.env"
MCP_ENV="$ROOT/.cursor/mcp.env"

if [[ ! -f "$BACKEND_ENV" ]]; then
  echo "Missing $BACKEND_ENV — copy backend/.env.example and add your keys first." >&2
  exit 1
fi

# shellcheck disable=SC1090
source "$BACKEND_ENV"

: "${VAPI_PRIVATE_KEY:?VAPI_PRIVATE_KEY not set in backend/.env}"
: "${INSFORGE_SERVICE_KEY:?INSFORGE_SERVICE_KEY not set in backend/.env}"
: "${INSFORGE_URL:?INSFORGE_URL not set in backend/.env}"

mkdir -p "$ROOT/.cursor"
cat >"$MCP_ENV" <<EOF
# Auto-generated by scripts/sync-mcp-env.sh — do not commit
VAPI_TOKEN=${VAPI_PRIVATE_KEY}
API_KEY=${INSFORGE_SERVICE_KEY}
API_BASE_URL=${INSFORGE_URL}
EOF

chmod 600 "$MCP_ENV"
echo "Wrote $MCP_ENV"
